apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rag-backend
  template:
    metadata:
      labels:
        app: rag-backend
    spec:
      containers:
      - name: backend
        image: sarveshkumar7/rag-backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: rag-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: rag-backend-service
spec:
  selector:
    app: rag-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP